### ISSUE TITLE
API Key?

### ISSUE THREAD

**Issue by seitzbg** [dgilland/omdb.py#14]
How does one use their API key with this module?

TIA,

**Comment by seitzbg** [comment]
Got it working with omdb.request.

**Comment by dgilland** [comment]
There's first-class support for this with [v0.8.1](https://pypi.python.org/pypi/omdb/0.8.1):

```python
import omdb

omdb.set_default('apikey', API_KEY)

# or
client = omdb.Client(apikey=API_KEY)
```
