### ISSUE TITLE
API_KEY is not defined 

### ISSUE THREAD

**Issue by lijhong** [dgilland/omdb.py#16]
when I follow the demo to use omdbapi ,but I get a error like this:

In [17]: from omdb import Client
    ...: 
In [18]: client = Client(apikey=API_KEY)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-18-221be7517bb8> in <module>()
----> 1 client = Client(apikey=API_KEY)
NameError: name 'API_KEY' is not defined

what should I do fix it?  thanks a lot.

**Comment by dgilland** [comment]
You need to specify the value of `API_KEY` using your OMDb API Key.
