### ISSUE TITLE
Rotten Tomatoes score

### ISSUE THREAD

**Issue by cyril94440** [dgilland/omdb.py#17]
Hi there,

for some reasons, it seems that the lib is unable to retrieve rottenTomatoes score.

I do have an API Key and I set tomatoes to True.
I fetch a movie that has a rotten tomatoes score on OMDB but in the result of the lib I get N/A for all tomatoes values.

Maybe something has been updated on the API but not the lib?

Thanks

**Comment by dgilland** [comment]
It's an issue upstream with omdbapi:

- https://github.com/omdbapi/OMDb-API/issues/5
- https://www.patreon.com/posts/rating-changes-8417367

**Comment by cyril94440** [comment]
It seems that they've updated the schema of the returned json as I am able to retrieve the scores using REST request.
The lib might need a bit of an update 😉

**Comment by dgilland** [comment]
This has been addressed in [v0.9.1](https://pypi.org/project/omdb/0.9.1/). Responses from omdb.py no longer exclude fields returned by OMDb API (the fields names are still converted to underscore case though). The Tomatoes scores are now in the "ratings" field along with scores from IMDB and Metacritic.
