### ISSUE TITLE
OMDBClient does bot have full functionality of the omdb module

### ISSUE THREAD

**Issue by karipov** [dgilland/omdb.py#18]
When I created a client and initialized it with the API key, when trying to use the search method I get the following error:

```
>>> client.search('True Grit')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'OMDBClient' object has no attribute 'search'
```
I've checked the `clients.py` file and it seems the client has access only to the `.get()` function.

Could you please add the rest of the functionality?

**Comment by dgilland** [comment]
Added in `v0.10.0`: https://pypi.org/project/omdb/0.10.0/
