### ISSUE TITLE
Add support for new "type" parameter from OMDB API

### ISSUE THREAD

**Issue by dgilland** [dgilland/omdb.py#2]

**Comment by ba1dr** [comment]
+1

**Comment by dgilland** [comment]
Closed via e0cf70cfe550f79e847689d3a0a8a64f57dd4017 and released as [v0.3.0](https://pypi.python.org/pypi/omdb?version=0.3.0).

The new parameter name is `media_type` which is now valid for all of the main API functions. For example:

```python
omdb.search(search_string, media_type='movie')
```

I've also added a few convenience functions for searching by media type:

- [search_movie](https://github.com/dgilland/omdb.py/blob/59dfb12e9f918a0b151f9936ea54d68e4413698f/omdb/api.py#L31)
- [search_episode](https://github.com/dgilland/omdb.py/blob/59dfb12e9f918a0b151f9936ea54d68e4413698f/omdb/api.py#L37)
- [search_series](https://github.com/dgilland/omdb.py/blob/59dfb12e9f918a0b151f9936ea54d68e4413698f/omdb/api.py#L43)
