### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by cgravdahl** [dgilland/omdb.py#4]
I want to use [Sourcegraph](https://sourcegraph.com) for omdb.py code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/dgilland/omdb.py. (It should only take 30 seconds.)

Thank you!

**Comment by dgilland** [comment]
Done: https://sourcegraph.com/github.com/dgilland/omdb.py
