### ISSUE TITLE
search_episode not working

### ISSUE THREAD

**Issue by cgomezmendez** [dgilland/omdb.py#6]
I've trying to make it work but it doesn't even with the example of the readme of search_episode it doesn't return anything, it is deprecated or something?

<pre>
>>> omdb.search_episode('True Grit')
Search([])
</pre>

This is my enviroment info:

<pre>
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
</pre>

**Comment by dgilland** [comment]
There seems to be a potential issue with the OMDb API itself.

For example, this (searching for a movie containing `"an"`) returns results:

http://www.omdbapi.com/?s=an&type=movie

but this (which is the URL used by `search_episode()`) returns nothing:

http://www.omdbapi.com/?s=an&type=episode

On http://omdbapi.com/, the parameter `type` is listed as being one of `movie`, `series`, or `episode`.

I contacted the owner of OMDb API about this (no reply yet). I'll update once I know more.

**Comment by cgomezmendez** [comment]
Any news on this?

**Comment by dgilland** [comment]
Nothing yet. No reply from the OMDb developer.

**Comment by cgomezmendez** [comment]
I suppose that maybe maintainer of OMDb changed the API but didn't update the documentation.
