### ISSUE TITLE
Documentation incorrect for imdb_id omdb.py field

### ISSUE THREAD

**Issue by p00gz** [dgilland/omdb.py#8]
Per official documentation found: https://media.readthedocs.org/pdf/omdbpy/latest/omdbpy.pdf
imdb_id field is incorrect in "Search Item" and "Get Item" documentation on GitHub. 
After some troubleshooting I found that omdb.get(imdbid='tt0043456')  does work.

**Comment by dgilland** [comment]
The specification of `imdb_id` in the `Search Item` and `Get Item` sections is referring to the output data's field name. Whereas the input parameter to the API methods is `imdbid`. Admittedly, this is not as clear as it could be in the docs.

Also it makes sense to have the input parameter match the output field if possible. So I could make the following changes:

- Make docs clearer with respect to input parameters vs output field names
- Make alias for input parameter `imdbid` as `imdb_id`

Thoughts?

**Comment by p00gz** [comment]
After looking over the repository docs a little more I think it just needs to be a little clearer. I was confused by the Get Item Fields section since I have been using the wrapper as such: 
#ttid being the imdb unique tt identifier
omdbSearch = omdb.get(imdb=ttId)
ombdYear = omdb.Search.year
etc
